# Generated by Django 4.1.1 on 2022-09-13 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='imc',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='id_paciente',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
