# Generated by Django 4.1.1 on 2022-09-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_pacientes_id_remove_pacientes_imc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='peso',
            field=models.FloatField(),
        ),
    ]
